import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import Post from '../_layouts/PostCard/post'
import Search from '../_layouts/search/search'
import { Layout, Pagination } from 'antd'
import { Content, Footer, Header } from 'antd/lib/layout/layout'
import HeaderLayout from '../_layouts/Header/Header'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next JS Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout className={styles.homePage}>
        <HeaderLayout/>
        <Content>
          <h2>Главная страница блога</h2>
        </Content>
        <Footer>
          Футер блога
        </Footer>
      </Layout>
    </div>
  )
}
