import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import Post from '../_layouts/PostCard/post'
import Search from '../_layouts/search/search'
import { Pagination } from 'antd'
import Header from '../_layouts/Header/Header'

export default function Posts({data}) {

    const [posts, setPosts] = useState(data)
    const [sortedPosts, setSortedPosts] = useState(posts)
    const [currentPage, setCurrentPage] = useState(1)
    const [pageSize, setPageSize] = useState(10)
    let from = currentPage * 10 - 10


    return (
        <div className={styles.container}>
        <Head>
            <title>Next JS Blog</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header/>
        <main className={styles.main}>
        <Search data={{posts, setSortedPosts}}/>
        <div className={styles.posts}>
            {sortedPosts.map((post, index) => index < currentPage * pageSize && index >= from ? <Post key={`post${post.id}`} data={{posts, setSortedPosts}} title={post.title} description={post.announce} id={post.id} photo={post.photo} category={post.category} tags={post.tags} /> : <></>)}
        </div>
        <Pagination style={{marginBottom: 10}} defaultCurrent={1} onShowSizeChange={(current, size) => {setPageSize(size)}} onChange={(page) => setCurrentPage(page)} total={sortedPosts.length} />
        </main>
        </div>
    )
}

export const getStaticProps = async () => {
    const response = await fetch(`${process.env.API_HOST}/posts`);
    const json = await response.json();
    const data = json.posts


    return {
        props: {data},
    }
} 